name: Create jira issue from github issue

on:
  issues:
    types: [opened]

jobs:
  update_jira:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Jira Create issue
        id: create
        uses: djzager/jira-create-issue-action@bearer-token
        with:
          jiraBaseUrl: https://issues.redhat.com
          project: MIG
          issuetype: Bug
          summary: ${{ github.event.issue.title }}
          labels: community
          jiraToken: ${{ secrets.JIRA_API_TOKEN }}
          description: |
            ${{ github.event.issue.body }}
            Created by github action.

      - name: Create comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            Automatically created Jira issue: ${{ steps.create.outputs.issue }}
          reaction-type: '+1'
